# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Faster builds
org.gradle.parallel=true
org.gradle.caching=true
android.experimental.run-jlink-in-separate-process=false
android.disallowKotlinSourceSets=false

# JDK Path
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C:\\Program Files\\Eclipse Adoptium\\jdk-25.0.2.10-hotspot,C:\\Program Files\\Android\\Android Studio\\jbr
