# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Faster builds
org.gradle.parallel=true
org.gradle.caching=true

# Fix for jlink / JRE errors - Use Android Studio's embedded JDK
android.experimental.run-jlink-in-separate-process=false
android.experimental.enableJdkImage=false
android.jdk.image=false
android.disallowKotlinSourceSets=false
