# Java path for Gradle daemon
toolchain.java.11.path=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot
toolchain.java.17.path=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot
toolchain.java.21.path=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.18.8-hotspot